# variations root: natives/stm/appsystem/ch/common/userdata/charactervariationcataloglistuserdata.user.2
# variations: natives/stm/appsystem/ch/ch230/userdata/ch230_variationcataloguserdata.user.2  (app.CharacterVariationCatalogUserdata.CatalogData)
