classes:
  app.GenerateTableData:
    id: [_TableID]
    group: spawns
    type: autoset_spawns

  app.GenerateRowData:
    id: [_ManualSetGuid, _AutoSetGuid] ## TODO: verify are these really unique?
    fields:
      _CharaID: { enum: app.CharacterID }
