# list of resources required for a new common NPC:
# - character data natives/stm/appsystem/ch/ch300/userdata/characterdatalist.user.2
# - head bake pfb (app.PartSwapTextureHolder pfb)
# -> catalog - natives/stm/appsystem/charaedit/ch000/catalog/headprebaketexturecatalog_npc.user.2
# - body bake pfb (app.PartSwapTextureHolder pfb)
# -> catalog - natives/stm/appsystem/charaedit/ch000/catalog/bodyprebaketexturecatalog_npc.user.2
# -> catalog _Hash is computed from "ch300000_0" - _0 or _1 for the main/replacement NPCs; does the value matter for anything, can we just pass in the chara ID?
# - npcart image (app.GUITextureHolder pfb) - natives/stm/appsystem/gui/prefab/textureholder/npcart/npcart_ch300002_00_00.pfb.17
# -> add to prefab list - natives/stm/appsystem/gui/userdata/newtextureholderdata/guinpcarttextureholderdata.user.2
# -> enum: app.GUITextureLoaderDefine.NPCArtTextureID, enum format "NPCArt_{charaId}_{variantId}_{costumeId?}"
# - add thumbnail (app.GUITextureHolder pfb) - natives/stm/appsystem/gui/prefab/textureholder/npcthumb/npcthumb_ch300000_00_00.pfb.17
# -> add to prefab list - natives/stm/appsystem/gui/userdata/newtextureholderdata/guinpcthumbnailtextureholderdata.user.2
# -> enum: app.GUITextureLoaderDefine.NPCThumbnailTextureID, enum format "NPCThumb_{charaId}_{variantId}_{costumeId?}"
# - corpse image (app.GUITextureHolder pfb) - natives/stm/appsystem/gui/prefab/textureholder/corpsethumb/corpsethumb_ch300002_00.pfb.17
# -> add to prefab list - natives/stm/appsystem/gui/userdata/newtextureholderdata/corpsethumbtextureholderdata.user.2
# -> enum: app.GUITextureLoaderDefine.CorpseThumbTextureID, enum format "CorpseThumb_{charaId}_{variantId}"
# - lipsync user file - natives/stm/appsystem/ch/lipsync/npc/ch300002.pfb.17
# -> catalog - natives/stm/appsystem/catalog/maincontents/userdata/lipsynccataloguserdata.user.2
# - textures - body (ALBD, NRRA), head (ALBD, NRRA)
# - appearance and costume data (app.charaedit.ch000.EditDataTable.Data) - natives/stm/appsystem/charaedit/ch000/editdatatable_npc.user.2
# - name "Mes_{_CharacterID:enum(app.CharacterID)}" (natives/stm/message/ui/charactername.msg.22)
# - NPC schedule - natives/stm/appsystem/ch/ch300/userdata/npcscheduledata.user.2
# - spawn them somewhere - natives/stm/appdata/generate/manualset/content/**/npc/normal/normal.user.2

# other, maybe useless?
# natives/stm/appdata/generate/manualset/simpleglobalnpcsettable.user.2
# natives/stm/appdata/generate/manualset/simpleglobalappendnpcsettable.user.2

entities:
  characters.npc_data:
    enums:
    - name: app.CharacterID
      format: "{name}"
      primary: true
    custom_id_range: [1000, 999999]
    to_string: "NPC {name}: {displayName}"
    fields:
      data:
        type: object
        label: Data
        required: true
        param:
          classname: app.CharacterData
          nested: false
      edit_data:
        type: object
        label: Customization
        param:
          classname: app.charaedit.ch000.EditDataTable.Data
          nested: false
      name:
        type: string
        label: NPC internal code name
        required: true
        param:
          regex: "^ch3[0-9_]{5}$"
          regexDescription: "Example: ch302345"
          tooltip: Enter a code name for the NPC. This should be unique across all characters, used for translation keys and file names.
          initial: "{id:enum_name(app.CharacterID)}"
          diffable: false
        display_after: start
      displayName:
        type: msg
        label: Name
        required: true
        param:
          key: "Mes_{name}" # if data._SubNPC -> _X1 suffix
          # key might not really matter, there's a NameID on the character data
          file: natives/stm/message/ui/charactername.msg.22
        display_after: name

classes:
  app.charaedit.ch000.EditDataTable.Data:
    id: [_CharacterID]
    to_string: "EditDataTable Character={_CharacterID:enum(app.CharacterID)}"
    patcher:
      type: array-file
      file: natives/stm/appsystem/charaedit/ch000/editdatatable_npc.user.2
  app.CharacterData:
    id: [ID]
    to_string: "{ID:enum_name(app.CharacterID)} {NameID:translate()}"
    patcher:
      type: array-file
      file: natives/stm/appsystem/ch/ch300/userdata/characterdatalist.user.2

  app.facial.LipSync.Phoneme:
    to_string: "Phoneme: SoundID={_SoundMediaID}, duration={_TotalTime}"
  app.facial.LipSync.Phoneme.KeyFrame:
    to_string: "Keyframe {_Time} Vowel={_Vowel}"
  app.PartSwapTextureHolder.MaterialParam:
    to_string: "MaterialParam: {_MaterialName}.{_VariableName} = {_Texture}"
  app.DecisionPack.Decision:
    to_string: "Decision Id={_UniqueId} {_ActInterPack}"
  app.NPCSchedule:
    to_string: "NPC Schedule ID={ID:enum(app.CharacterID)} {Comments}"
  app.LipSyncCatalogUserData.PlayerElement:
    to_string: "Player Data: {_Voice:enum(app.SoundVoiceManager.PlayerVoiceType)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.PawnElement:
    to_string: "Pawn Data: {_Voice:enum(app.SoundVoiceManager.PawnPersonalityType)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.NPCElement:
    to_string: "Generic NPC Data: {_Voice:enum(app.CharacterData.VoiceDefine)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.CharacterElement:
    to_string: "NPC Data: {_CharacterID:enum(app.CharacterID)}"
