classes:
  via.physics.Collider:
    to_string: "Collider: {Shape?.class_shortname} {CollisionFilter}"
  via.render.CompositeMeshInstanceGroup:
    to_string: "Group ({Transform.Count}) - {Mesh}"
  via.dynamics.CompositeRigidBodyMeshSet.MeshInfo:
    to_string: "RB MeshSet - {Position} {Resource}"
