# TODO do we need these? natives/stm/_chainsaw/appsystem/ui/userdata/gamestatsuserdata.user.2, natives/stm/_anotherorder/appsystem/ui/userdata/gamestatsuserdata_ao.user.2

entities:
  weapon:
    enums:
    - name: chainsaw.WeaponID
      format: "{name}"
      primary: true
    to_string: "Weapon {name} {displayName}"
    fields:
      data:
        type: object
        label: Data
        required: true
        param:
          classname: chainsaw.WeaponCatalogUserData.Data
      name:
        type: string
        label: Weapon code name
        required: true
        param:
          regex: "^wp[0-9_]+$"
          regexDescription: "Example: wp6000"
          tooltip: Enter a code name for the weapon. This should be unique across all weapons and is used for enum entries.
          initial: "{id:enum(chainsaw.WeaponID)}"
        display_after: start
      displayName:
        type: msg
        required: true
        param:
          key: "CH_Mes_Main_WEAPON_NAME_{name:upper()}_00_0_000"
          file: natives/stm/_chainsaw/message/mes_main_item/ch_mes_main_item_name.msg.22
        display_after: name
      equip_data:
        type: object
        label: Equip data
        param:
          classname: chainsaw.WeaponEquipParamCatalogUserData.Data
          nested: true
      upgrades:
        type: object
        label: Upgrades
        param:
          classname: chainsaw.WeaponDetailCustomUserdata.WeaponDetailStage
      prefab:
        type: resource
        label: Weapon prefab
        required: true
        param:
          type: Prefab
          path: "{data?._Prefab?.Path}"

classes:
  chainsaw.WeaponCatalogUserData.Data:
    id: [_WeaponID]
    to_string: "Weapon {_WeaponID:enum(chainsaw.WeaponID)} {_Prefab.Path}"
    patcher:
      type: array-file
      file: natives/stm/_chainsaw/appsystem/weapon/weaponcataloguserdata_1st.user.2
  chainsaw.WeaponEquipParamCatalogUserData.Data:
    id: [_WeaponID]
    to_string: "Weapon {_WeaponID:enum(chainsaw.WeaponID)}"
    patcher:
      type: array-file
      file: natives/stm/_anotherorder/appsystem/weapon/weaponequipparamcataloguserdata_ao.user.2
  chainsaw.WeaponDetailCustomUserdata.WeaponDetailStage:
    id: [_WeaponID]
    to_string: "Weapon {_WeaponID:enum(chainsaw.WeaponID)}"
    patcher:
      type: array-file
      file: natives/stm/_anotherorder/appsystem/weaponcustom/weapondetailcustomuserdata_ao.user.2
  chainsaw.WeaponDetailCustomUserdata.CommonCustom:
    to_string: "{_CommonCustomCategory:enum(chainsaw.CommonCustomCategory)}"
  chainsaw.WeaponDetailCustomUserdata.IndividualCustom:
    to_string: "{_IndividualCustomCategory:enum(chainsaw.IndividualCustomCategory)}"
  chainsaw.WeaponDetailCustomUserdata.AttachmentCustom:
    to_string: "{_ItemID:enum(chainsaw.ItemID)}"
  chainsaw.WeaponDetailCustomUserdata.AttachmentParam:
    to_string: "{_AttachmentParamName:enum(chainsaw.AttachmentParamName)}"
  chainsaw.WeaponDetailCustomUserdata.LimitBreakCustom:
    to_string: "{_LimitBreakCustomCategory:enum(chainsaw.LimitBreakCustomCategory)}"
