name: Build the app

on: push

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
        lfs: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish debug build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        cd ContentEditor.App
        dotnet publish -c Debug --no-restore -f net8.0-windows /p:VersionSuffix=${{ github.sha }} -o build ContentEditor.App

    - name: Publish release build
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=${{ github.ref_name }}
        cd ContentEditor.App
        dotnet publish -c Release --no-restore -f net8.0-windows /p:DebugType=none /p:DebugSymbols=false /p:VersionPrefix=${TAG#v} -o build ContentEditor.App
        rm -rf build/runtimes/linux-*
        rm -rf build/runtimes/osx*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ContentEditor
        path: "build/"
        include-hidden-files: true

    - name: ZIP files for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd build/
        7z a ContentEditor.zip *
    - name: Upload files to release
      uses: softprops/action-gh-release@v2.2.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "build/*.zip"
